name: Deploy .NET Application in Azure

on:
  workflow_dispatch:
  push:
    branches:
    - maindesativado

env:
  AZURE_WEBAPP_NAME: phase2
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.2.0
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore
        run: dotnet restore ./FIAP.PhaseOne.sln
        
      - name: Build
        run: dotnet build ./FIAP.PhaseOne.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./FIAP.PhaseOne.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
      - name: Test
        run: dotnet test ./FIAP.PhaseOne.sln --verbosity normal                    
      - name: Deployment
        uses: Azure/webapps-deploy@v3.0.0
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
